name: Build Docker Image

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: GersonRS/modern-gitops-stack/.github/workflows/modules-docker-build-push.yaml@main
    with:
      image_name: ${{ github.repository }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}