name: Atualizar README

on:
  pull_request:
    paths:
      - requirements.txt


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extrair Bibliotecas do requirements.txt
        id: extract-libraries
        run: |
          QUOTE=$(grep -v '^#' requirements.txt | grep -v '^-' | awk '{print "* `" $0 "`"}' | paste -sd '\n' -)
          echo -e "$QUOTE" > file.txt
      - name: Atualizar README.adoc
        run: |-
          # Set a default quote if the
          echo "${QUOTE:=>Silence is Golden}"
          # Disable interpreting exclamation mark! as a command
          histchars=
          # Set delimiters to variables
          start_delimiter="<!-- start-quote -->"
          end_delimiter="<!-- end-quote -->"
          # Remove previous quote with its delimter
          sed -i "/$start_delimiter/,/$end_delimiter/d" README.md
          # Add the new quote to the README file
          printf "$start_delimiter\n$QUOTE\n$end_delimiter\n" >> README.md

      - name: Commit das alterações
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(action): generate docs and write to README.adoc"
          file_pattern: README.md
